[package]
name = "homecentral_backend"
version = "0.1.0"
authors = ["Rainer Schoenberger <rainer-homecentral@wwad.de>"]
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["sync", "rt-multi-thread", "macros"] }
by_address = {version = "1"}